<?php
/**
 * 
 * @param $grid 
 * 
 * partial script
 * partial/block/panel.phtml
 * 
 */
?>
<div id="panel-resource" class="panel panel-default">
    <div class="panel-collapse panel-heading">
        <div class="panel-title"><?php print $panel["title"] ?></div>
    </div>
    <div class="panel-collapse panel-body"><?php print $panel["body"] ?></div>
    <div class="panel-collapse panel-footer"><?php print $panel["footer"] ?></div>
</div>

<script type="text/javascript">
//    var panel = $('#panel-resource');
//    $(function() {
//        
//    });
</script>