<ul class="list-inline pull-right">
    <li><a href="<?= $this->url() . 'view' ?>" disabled="disabled" alt="просмотр">просмотр</a></li>
    <li><a href="<?= $this->url() . 'add' ?>" disabled="disabled" alt="просмотр">создать</a></li>
    <li><a href="<?= $this->url() . 'edit' ?>" disabled="disabled" alt="просмотр">изменить</a></li>
    <li><a href="<?= $this->url() . 'delete' ?>" disabled="disabled" alt="просмотр">удалить</a></li>
</ul>
<div class="clearfix"></div>

