<?php
print sprintf('%s' . $this->translate('A 404 error occurred') . '%s', '<h1>', '</h1>');
print sprintf('%s' . $this->message . '%s', '<h2>', '</h2>');

if (isset($this->reason) && $this->reason):
    $message = '';
    switch ($this->reason)
    {
	case 'error-controller-cannot-dispatch':
	    $message = $this->translate('The requested controller was unable to dispatch the request.');
	    break;
	case 'error-controller-not-found':
	    $message = $this->translate('The requested controller could not be mapped to an existing controller class.');
	    break;
	case 'error-controller-invalid':
	    $message = $this->translate('The requested controller was not dispatchable.');
	    break;
	case 'error-router-no-match':
	    $message = $this->translate('The requested URL could not be matched by routing.');
	    break;
	default:
	    $message = $this->translate('We cannot determine at this time why a 404 was generated.');
	    break;
    }
    print sprintf('%s' . $this->translate('We cannot determine at this time why a 404 was generated.') . '%s', '<p>', '</p>');
endif;
if (isset($this->controller) && $this->controller):

    print '<dl>';
    print sprintf('%s' . $this->translate('Controller') . '%s', '<dt>', '</dt>');
    $message = (string) '';
    $message .= $this->escapeHtml($this->controller);
    if ((isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller)):
	$message .= '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
    endif;
    print sprintf('%s' . $message . '%s', '<dd>', '</dd>');

//    <!--<dl><dt>-->
	// echo $this->translate('Controller') :</dt>
//        <!--<dd>--> 
// echo $this->escapeHtml($this->controller) 
//	    if (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller):
//		echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
//	    endif;
//        <!--</dd>    </dl>-->
endif;

if (isset($this->display_exceptions) && $this->display_exceptions): 
    if (isset($this->exception) && $this->exception instanceof Exception): 
	?>
	<hr/>
	<h2><?php echo $this->translate('Additional information') ?>:</h2>
	<h3><?php echo get_class($this->exception); ?></h3>
	<dl>
	    <dt><?php echo $this->translate('File') ?>:</dt>
	    <dd>
		<pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
	    </dd>
	    <dt><?php echo $this->translate('Message') ?>:</dt>
	    <dd>
		<pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
	    </dd>
	    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
	    <dd>
		<pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
	    </dd>
	</dl>
	<?php
	$e = $this->exception->getPrevious();
	if ($e) :
	    ?>
	    <hr/>
	    <h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
	    <ul class="unstyled">
		<?php while ($e) : ?>
		    <li>
			<h3><?php echo get_class($e); ?></h3>
			<dl>
			    <dt><?php echo $this->translate('File') ?>:</dt>
			    <dd>
				<pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
			    </dd>
			    <dt><?php echo $this->translate('Message') ?>:</dt>
			    <dd>
				<pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
			    </dd>
			    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
			    <dd>
				<pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
			    </dd>
			</dl>
		    </li>
		    <?php
		    $e = $e->getPrevious();
		endwhile;
		?>
	    </ul>
	<?php endif; ?>

    <?php else: ?>

	<h3><?php echo $this->translate('No Exception available') ?></h3>

    <?php endif ?>

    <?php



 endif ?>
