<div class="input-group">
    <input type="text" class="form-control" placeholder="поиск в:">
    <div class="input-group-btn">
	<button type="button" class="btn btn-default" tabindex="-1"><span class="glyphicon glyphicon-search"></span></button>
	<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
	    <span class="caret"></span>
	    <span class="sr-only">Toggle Dropdown</span>
	</button>
	<ul class="dropdown-menu dropdown-menu-right" role="menu">
	    <li><a href="#">Action</a></li>
	    <li><a href="#">Another action</a></li>
	    <li><a href="#">Something else here</a></li>
	    <li class="divider"></li>
	    <li><a href="#">Separated link</a></li>
	</ul>
    </div>
</div>